server:
  port: 8085

spring:
  application:
    name: billing-service
  datasource:
    url: jdbc:mysql://localhost:3306/billing?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.medlab.billing.controller
  paths-to-match: /**

logging:
  level:
    com.medlab.billing: DEBUG
    org.springframework.security: INFO
    feign: DEBUG